name: Kernel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Cache apt-install
      uses: awalsh128/cache-apt-pkgs-action@v1.1.2
      with:
        packages: clang llvm lld
        
    - name: Set up NASM
      uses: ilammy/setup-nasm@v1.4.0

    - name: Build
      run: make
    
    - name: Upload
      uses: actions/upload-artifact@v3.1.1
      with:
        name: kernel
        path: positron.elf
