name: Kernel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1.6.0
      with:
        version: 15.0.4
      
    - name: Set up NASM
      uses: ilammy/setup-nasm@v1.4.0

    - name: Build
      run: make
    
    - name: Upload
      uses: actions/upload-artifact@v3.1.1
      with:
        name: kernel
        path: positron.elf
