name: Kernel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Cache apt-install
      uses: daaku/gh-action-apt-install@v4
      with:
        packages: clang llvm lld nasm

    - name: Build
      run: make
    
    - name: Upload
      uses: actions/upload-artifact@v3.1.1
      with:
        name: kernel
        path: positron.elf
