name: Kernel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Clang
      uses: egor-tensin/setup-clang@v1

    - name: Set up NASM
      uses: ilammy/setup-nasm@v1.4.0

    - name: Build
      run: make
    
    - name: Upload
      uses: actions/upload-artifact@v3.1.1
      with:
        name: kernel
        path: positron.elf
